---
version: '3'

services:
  db:
    image: postgres:15.1-alpine
    container_name: vpark-pg
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=ventilar_db
  test-db:
    image: postgres:15.1-alpine
    container_name: vpark-pg-test
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=test_ventilar_db

networks:
  default:
    name: gabtec-vnet
    external: true
