---
version: '3'

services:
  db:
    image: postgres:15.1-alpine
    container_name: ventilar-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db_dump:/backups
  test-db:
    image: postgres:15.1-alpine
    container_name: ventilar-db-test
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

networks:
  default:
    name: gabtec-vnet
    external: true
