apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: ventilar

images:
- name: ventilar-api
  newName: gabtec/ventilar-api
  newTag: 85a0bcf1442da784674434e47548c81900c87fbe
