---
apiVersion: v1
kind: Service
metadata:
  name: ventilar-api-service
spec:
  selector:
    app: ventilar-api
  # type: LoadBalancer | ClusterIP | NodePort
  ports:
    - name: api-port
      port: 3002 # service port
      targetPort: 3002 # container port
