name: Build Docker Image CI

on: workflow_dispatch
# on:
#   push:
#     branches: [ "main" ]
# pull_request:
#   branches: [ "main" ]

# workflow global variables
env:
  REG_URL: reg.gabtec.pt/xgeeks/
  REG_USER: xpto
  REG_PASSW: xpto
  PROJ_NAME: gh-ventilar-api
  PROJ_VERSION: v0.0.5
  NODE_ENV: production
  API_SRV_PORT: 3002
  DB_DRIVER: postgres
  DB_HOST: localhost
  DB_PORT: 5432
  DB_USER: admin
  DB_PASSWORD: admin
  DB_NAME: ventilar_db
  ACCESS_TOKEN_SECRET: foo
  ACCESS_TOKEN_DURATION: 600000 #10m
  REFRESH_TOKEN_SECRET: bar
  REFRESH_TOKEN_DURATION: 86400000 #1d

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Print the Docker image
        run: echo $REG_URL$PROJ_NAME:$PROJ_VERSION
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag $REG_URL$PROJ_NAME:$PROJ_VERSION
          docker tag $REG_URL$PROJ_NAME:$PROJ_VERSION $REG_URL$PROJ_NAME:latest
      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: reg.gabtec.pt
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASSW }}
      - name: Upload to registry
        run: |
          docker push $REG_URL$PROJ_NAME:$PROJ_VERSION
          docker push $REG_URL$PROJ_NAME:$latest
