name: Build For E2E Testing CI

on: workflow_dispatch

env:
  REG_URL: reg.gabtec.pt/xgeeks/
  PROJ_NAME: gh-ventilar-api
  PROJ_VERSION: v0.0.6

jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15.1-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin
          POSTGRES_DB: ventilar_db_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: create env file for testing
        run: |
          touch .env
          echo API_SRV_PORT=3002 >> .env
          echo DB_DRIVER=postgres >> .env
          echo DB_HOST=localhost >> .env
          echo DB_PORT=5432 >> .env
          echo DB_USER=admin >> .env
          echo DB_PASSWORD=admin >> .env
          echo DB_NAME=ventilar_db >> .env
          echo ACCESS_TOKEN_SECRET=foo >> .env
          echo ACCESS_TOKEN_DURATION=60 >> .env
          echo REFRESH_TOKEN_SECRET=bar >> .env
          echo REFRESH_TOKEN_DURATION=86400 >> .env
          cat .env

      - name: Cache dependencies
        id: cached-install
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-${{ hashFiles('**/package-lock.json') }}
      - name: Run install
        if: steps.cached-install.outputs.cache-hit != 'true'
        run: npm install --quiet
      - name: Run build
        run: npm run build
      - name: Generate db migrations
        run: npm run migration:generate:all
      - name: Run db migrations
        run: npm run migration:run
      - name: Run db seeds
        run: npm run test:db:seed
      - name: Run tests
        run: npm run test
