name: Build Docker Image CI

on:
  push:
    branches: ['main']
  workflow_dispatch:
# pull_request:
#   branches: [ "main" ]

# workflow global variables
env:
  REG_URL: gabtec/oss-xgeeks
  PROJ_NAME: ventilar-api
  # PROJ_VERSION: v0.0.6

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REG_URL }}.docker.io
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.REG_URL }}/goapp:latest, ${{ secrets.REG_URL }}/goapp:${{ github.sha }}
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Kustomize in this worker
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: v5.0.1 #sos
      - name: Runs Kustomize to update k8s manifest file
        run: |
          cd k8s
          kustomize edit set image ventilar-api=${REG_URL}/ventilar-api:${GITHUB_SHA}
          cat kustomization.yaml
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "CD Action"
          git commit -am "ci: update `ventilar-api` image tag"
      # git push vai falhar porque no meu repo um user desconhecido is not allowed to push
      - name: Push changes
        uses: ad-m/github-push-action@master
        # must go to repo > settings > general (scroll down) and allow workflow permissions to write
